
name: "CI"
on: [push]

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    container: openjdk:8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
            maven-version: 3.9.1
      - name: "Build"
        run: |
          mvn package # TODO: is this enough?
      - name: "Upload jars"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "jars"
          path: "**/*.jar"
      - name: "Upload test results"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "build-results"
          path: "**/build/reports"
